
image:
  - Visual Studio 2017

platform:
  - x86
  - x64
  #- Any CPU

build_script:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
  - cmd: cd build && mkdir win && cd win
  - cmd: cmake -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=outputs ..\..
  - cmd: nmake
  - cmd: nmake install
  - cmd: nmake dist

for:
-
  matrix:
    only:
      #- platform: x86
      - platform: x64
      #- platform: Any CPU

  test_script:
    - cd outputs\bin
    - start /b elatests.exe --robot -c ..\etc\carrier\tests.conf && elatests.exe --cases -c ..\etc\carrier\tests.conf -r 3
