
image: Visual Studio 2017

platform:
  - x86
  - x64
  #- Any CPU

build_script:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
  - cmd: cd build && mkdir win && cd win
  - cmd: cmake -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=outputs ..\..
  - cmd: nmake
  - cmd: nmake install
  - cmd: nmake dist
  - cmd: set packagename=%APPVEYOR_BUILD_FOLDER%\%APPVEYOR_REPO_TAG_NAME%-windows-x64-%date:~10,4%%date:~7,2%%date:~4,2%.zip
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          7z a -tzip $env:packagename  .\outputs\*
      }

for:
-
  matrix:
    only:
      #- platform: x86
      - platform: x64
      #- platform: Any CPU

  test_script:
    - cd outputs\bin
    - start /b elatests.exe --robot -c ..\etc\carrier\tests.conf && elatests.exe --cases -c ..\etc\carrier\tests.conf -r 3

artifacts:
  - path: '*.zip'

deploy:
  provider: GitHub
  artifacts:
  auth_token:
    secure: Ydv3jxxAP6HvexomaFRj4cXpoUomi/NfumB/eWeGW2Qt/qA7xLdq+EXeQpdpVfi+
  draft: false
  prerelease: false
  on:
    # branch: master
    platform: x64
    APPVEYOR_REPO_TAG: true

