language: c

matrix:
  include:
  - os: osx
    env: BUILD_ENV=darwin_x64_debug
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir $BUILD_ENV && cd $BUILD_ENV && cmake ../..
      - make && make install && make dist

  - os: osx
    sudo: true
    env: BUILD_ENV=ios_arm64_debug
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir $BUILD_ENV && cd $BUILD_ENV
      - cmake -DIOS_PLATFORM=iphoneos -DCMAKE_TOOLCHAIN_FILE=../../cmake/iOSToolchain.cmake ../..
      - make && make install && make dist

  - os: osx
    sudo: true
    env: BUILD_ENV=ios_x64_debug
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir $BUILD_ENV && cd $BUILD_ENV
      - cmake -DIOS_PLATFORM=iphonesimulator -DCMAKE_TOOLCHAIN_FILE=../../cmake/iOSToolchain.cmake ../..
      - make && make install && make dist

  - env: BUILD_ENV=linux_x64_debug
    sudo: true
    install:
      - sudo apt-get update
      # if sphinx is 1.8.0，python version required 2.7.9 or newer
      - sudo apt-get install python3.4
      - sudo ln -s -f /usr/bin/python3.4 /usr/bin/python
      - sudo apt-get install doxygen  graphviz
      - curl -L -o /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py
      - sudo python /tmp/get-pip.py
      - sudo pip install breathe
      - sudo pip install -U sphinx
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir $BUILD_ENV && cd $BUILD_ENV && cmake -DENABLE_DOCS=ON ../..
      - make && sudo make install && sudo make dist

  - env: BUILD_ENV=linux_x64_release
    sudo: true
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir $BUILD_ENV && cd $BUILD_ENV && cmake -DCMAKE_BUILD_TYPE=Release ../..
      - make && sudo make install && sudo make dist

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=android_armv7a_debug
    install:
      - echo y | sdkmanager 'ndk-bundle'
      - export ANDROID_NDK_HOME=/usr/local/android-sdk/ndk-bundle
      - cd /tmp && wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz
      - tar -xzvf cmake-3.11.4-Linux-x86_64.tar.gz
      - export PATH=/tmp/cmake-3.11.4-Linux-x86_64/bin:$PATH
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir $BUILD_ENV && cd $BUILD_ENV
      - cmake -DANDROID_ABI=armeabi-v7a -DCMAKE_TOOLCHAIN_FILE=../../cmake/AndroidToolchain.cmake ../..
      - make && make install && make dist

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=android_arm64_debug
    install:
      - echo y | sdkmanager 'ndk-bundle'
      - export ANDROID_NDK_HOME=/usr/local/android-sdk/ndk-bundle
      - cd /tmp && wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz
      - tar -xzvf cmake-3.11.4-Linux-x86_64.tar.gz
      - export PATH=/tmp/cmake-3.11.4-Linux-x86_64/bin:$PATH
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir $BUILD_ENV && cd $BUILD_ENV
      - cmake -DANDROID_ABI=arm64-v8a -DCMAKE_TOOLCHAIN_FILE=../../cmake/AndroidToolchain.cmake ../..
      - make && make install && make dist

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=android_x86_debug
    install:
      - echo y | sdkmanager 'ndk-bundle'
      - export ANDROID_NDK_HOME=/usr/local/android-sdk/ndk-bundle
      - cd /tmp && wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz
      - tar -xzvf cmake-3.11.4-Linux-x86_64.tar.gz
      - export PATH=/tmp/cmake-3.11.4-Linux-x86_64/bin:$PATH
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir $BUILD_ENV && cd $BUILD_ENV
      - cmake -DANDROID_ABI=x86 -DCMAKE_TOOLCHAIN_FILE=../../cmake/AndroidToolchain.cmake ../..
      - make && make install && make dist

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=android_x86_64_debug
    install:
      - echo y | sdkmanager 'ndk-bundle'
      - export ANDROID_NDK_HOME=/usr/local/android-sdk/ndk-bundle
      - cd /tmp && wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz
      - tar -xzvf cmake-3.11.4-Linux-x86_64.tar.gz
      - export PATH=/tmp/cmake-3.11.4-Linux-x86_64/bin:$PATH
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir $BUILD_ENV && cd $BUILD_ENV
      - cmake -DANDROID_ABI=x86_64 -DCMAKE_TOOLCHAIN_FILE=../../cmake/AndroidToolchain.cmake ../..
      - make && make install && make dist

  - sudo: true
    env: BUILD_ENV=raspberrypi_debug
    install:
      - cd /tmp
      - git clone https://github.com/raspberrypi/tools.git raspberrypitools
      - export RPI_TOOLCHAIN_HOME=/tmp/raspberrypitools
      - cd /tmp && wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz
      - tar -xzvf cmake-3.11.4-Linux-x86_64.tar.gz
      - export PATH=/tmp/cmake-3.11.4-Linux-x86_64/bin:$PATH
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir rpi && cd rpi
      - cmake -DCMAKE_TOOLCHAIN_FILE=../../cmake/RPiToolchain.cmake ../..
      - make && make install && make dist

