language: c

matrix:
  include:
  - env: BUILD_ENV=linux_build
    install:
      - sudo apt-get update
      - sudo apt-get install doxygen python-sphinx graphviz
      - curl -L -o /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py
      - sudo python /tmp/get-pip.py
      - sudo pip install breathe
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir linux && cd linux && cmake -DENABLE_DOCS=ON ../.. && make

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=arm_android_32
    install:
      - echo y | sdkmanager 'ndk-bundle'
      - export ANDROID_NDK_HOME=/usr/local/android-sdk/ndk-bundle
      - cd /tmp && wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz
      - tar -xzvf cmake-3.11.4-Linux-x86_64.tar.gz
      - export PATH=/tmp/cmake-3.11.4-Linux-x86_64/bin:$PATH
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir arm_android_32 && cd arm_android_32
      - cmake -DANDROID_ABI=armeabi-v7a -DCMAKE_TOOLCHAIN_FILE=../../cmake/AndroidToolchain.cmake ../..
      - make && make install && make dist

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=arm_android_64
    install:
      - echo y | sdkmanager 'ndk-bundle'
      - export ANDROID_NDK_HOME=/usr/local/android-sdk/ndk-bundle
      - cd /tmp && wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz
      - tar -xzvf cmake-3.11.4-Linux-x86_64.tar.gz
      - export PATH=/tmp/cmake-3.11.4-Linux-x86_64/bin:$PATH
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir arm_android_64 && cd arm_android_64
      - cmake -DANDROID_ABI=arm64-v8a -DCMAKE_TOOLCHAIN_FILE=../../cmake/AndroidToolchain.cmake ../..
      - make && make install && make dist

  - sudo: true
    env: BUILD_ENV=RaspberryPi_build
    install:
      - cd /tmp
      - git clone https://github.com/raspberrypi/tools.git raspberrypitools
      - export RPI_TOOLCHAIN_HOME=/tmp/raspberrypitools
      - cd /tmp && wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz
      - tar -xzvf cmake-3.11.4-Linux-x86_64.tar.gz
      - export PATH=/tmp/cmake-3.11.4-Linux-x86_64/bin:$PATH
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir rpi && cd rpi
      - cmake -DCMAKE_TOOLCHAIN_FILE=../../cmake/RPiToolchain.cmake ../..
      - make && make install && make dist

  - os: osx
    env: BUILD_ENV=darwin_build
    script: cd $TRAVIS_BUILD_DIR/build && mkdir darwin && cd darwin && cmake ../.. && make

  - os: osx
    sudo: true
    env: BUILD_ENV=iOS_build
    script:
      - cd $TRAVIS_BUILD_DIR/build && mkdir iOS && cd iOS
      - cmake -DIOS_PLATFORM=iphoneos -DCMAKE_TOOLCHAIN_FILE=../../cmake/iOSToolchain.cmake ../..
      - make && make install && make dist
