language: c

matrix:
  include:
  - os: osx
    env: BUILD_ENV=darwin_x64 BUILD_TYPE=Debug RUN_TEST=ON
    if: |
      NOT tag IS present OR \
      tag =~ /^(internal-test)/

  - os: osx
    env: BUILD_ENV=darwin_x64 BUILD_TYPE=Release RUN_TEST=ON
    if: |
      NOT tag =~ /^(internal-test)/

  - os: osx
    env: BUILD_ENV=ios_arm64 PLATFORM=iphoneos BUILD_TYPE=Debug
    if: |
      NOT tag IS present OR \
      tag =~ /^(internal-test)/

  - os: osx
    env: BUILD_ENV=ios_arm64 PLATFORM=iphoneos BUILD_TYPE=Release
    if: |
      tag IS present AND \
      NOT tag =~ /^(internal-test)/

  - os: osx
    env: BUILD_ENV=ios_x64 PLATFORM=iphonesimulator BUILD_TYPE=Debug
    if: |
      NOT tag IS present OR \
      tag =~ /^(internal-test)/

  - os: osx
    env: BUILD_ENV=ios_x64 PLATFORM=iphonesimulator BUILD_TYPE=Release
    if: |
      tag IS present AND \
      NOT tag =~ /^(internal-test)/

  - env: BUILD_ENV=linux_x64 BUILD_TYPE=Debug RUN_TEST=ON
    sudo: true
    if: |
      NOT tag IS present OR \
      tag =~ /^(internal-test)/

  - env: BUILD_ENV=linux_x64 ENABLE_DOCS=ON BUILD_TYPE=Release RUN_TEST=ON
    sudo: true
    if: |
      NOT tag =~ /^(internal-test)/

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=android_armv7a ANDROID_ABI=armeabi-v7a BUILD_TYPE=Debug
    if: |
      NOT tag IS present OR \
      tag =~ /^(internal-test)/

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=android_armv7a ANDROID_ABI=armeabi-v7a BUILD_TYPE=Release
    if: |
      tag IS present AND \
      NOT tag =~ /^(internal-test)/

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=android_arm64 ANDROID_ABI=arm64-v8a BUILD_TYPE=Debug
    if: |
      NOT tag IS present OR \
      tag =~ /^(internal-test)/

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=android_arm64 ANDROID_ABI=arm64-v8a BUILD_TYPE=Release
    if: |
      tag IS present AND \
      NOT tag =~ /^(internal-test)/

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=android_x86 ANDROID_ABI=x86 BUILD_TYPE=Debug
    if: |
      NOT tag IS present OR \
      tag =~ /^(internal-test)/

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=android_x86 ANDROID_ABI=x86 BUILD_TYPE=Release
    if: |
      tag IS present AND \
      NOT tag =~ /^(internal-test)/

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=android_x86_64 ANDROID_ABI=x86_64 BUILD_TYPE=Debug
    if: |
      NOT tag IS present OR \
      tag =~ /^(internal-test)/

  - language: android
    sudo: true
    android:
      components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-21
    env: BUILD_ENV=android_x86_64 ANDROID_ABI=x86_64 BUILD_TYPE=Release
    if: |
      tag IS present AND \
      NOT tag =~ /^(internal-test)/

  - sudo: true
    env: BUILD_ENV=raspberrypi RASPBERRRIPI=TRUE BUILD_TYPE=Debug
    if: |
      NOT tag IS present OR \
      tag =~ /^(internal-test)/

  - sudo: true
    env: BUILD_ENV=raspberrypi RASPBERRRIPI=TRUE BUILD_TYPE=Release
    if: |
      tag IS present AND \
      NOT tag =~ /^(internal-test)/

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$ENABLE_DOCS" != "" ]]; then
        sudo apt-get update;
        sudo apt-get install python3.4;
        sudo ln -s -f /usr/bin/python3.4 /usr/bin/python;
        sudo apt-get install doxygen  graphviz;
        curl -L -o /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py;
        sudo python /tmp/get-pip.py;
        sudo pip install breathe;
        sudo pip install -U sphinx;
      fi

      if [[ "$ANDROID_ABI" == "" ]]; then
        if [[ "$RASPBERRRIPI" != "" ]]; then
          cd /tmp;
          git clone https://github.com/raspberrypi/tools.git raspberrypitools;
          export RPI_TOOLCHAIN_HOME=/tmp/raspberrypitools;
          wget -q https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz;
          tar -xzf cmake-3.11.4-Linux-x86_64.tar.gz;
          export PATH=/tmp/cmake-3.11.4-Linux-x86_64/bin:$PATH;
        fi
      else
        cd /tmp;
        wget -q https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz;
        tar -xzf cmake-3.11.4-Linux-x86_64.tar.gz;
        export PATH=/tmp/cmake-3.11.4-Linux-x86_64/bin:$PATH;
        wget -q https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip;
        unzip -q android-ndk-r16b-linux-x86_64.zip;
        export ANDROID_NDK_HOME=/tmp/android-ndk-r16b;
      fi
    else
      ulimit -c unlimited;
      sudo sysctl kern.corefile=/cores/core;
      easy_install six;
    fi

script:
  - cd $TRAVIS_BUILD_DIR/build && mkdir ${BUILD_ENV}_$BUILD_TYPE && cd ${BUILD_ENV}_$BUILD_TYPE
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export OUTPUT_TYPE=so;
      if [[ "$ANDROID_ABI" == "" ]]; then
        if [[ "$RASPBERRRIPI" == "" ]]; then
          cmake -DCMAKE_INSTALL_PREFIX=dist -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_DOCS=$ENABLE_DOCS ../.. ;
        else
          cmake -DCMAKE_INSTALL_PREFIX=dist -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=../../cmake/RPiToolchain.cmake ../.. ;
        fi
      else
        cmake -DANDROID_ABI=$ANDROID_ABI -DCMAKE_INSTALL_PREFIX=dist -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=../../cmake/AndroidToolchain.cmake ../.. ;
      fi
    else
      export OUTPUT_TYPE=dylib;
      if [[ "$PLATFORM" == "" ]]; then
        cmake -DCMAKE_INSTALL_PREFIX=dist -DCMAKE_BUILD_TYPE=BUILD_VER ../.. ;
      else
        cmake -DIOS_PLATFORM=$PLATFORM -DCMAKE_INSTALL_PREFIX=dist -DCMAKE_BUILD_TYPE=BUILD_VER -DCMAKE_TOOLCHAIN_FILE=../../cmake/iOSToolchain.cmake ../.. ;
      fi
    fi
  - make && make install && make dist && cd dist
  - if [[ "$RUN_TEST" != "" ]]; then
      cd bin && export LD_LIBRARY_PATH=../lib;
      ./elatests --robot -c ../etc/carrier/tests.conf &
      ./elatests --cases -c ../etc/carrier/tests.conf -r 3;
    fi

after_success:
  - if [[ "$TRAVIS_TAG" != "" ]]; then
      cd $TRAVIS_BUILD_DIR/build/${BUILD_ENV}_$BUILD_TYPE/dist;
      tar -czf $TRAVIS_TAG-$BUILD_ENV-$(date +'%Y%m%d').tar.gz include lib/*.$OUTPUT_TYPE;
      if [[ "$ENABLE_DOCS" != "" ]]; then
        tar -czf $TRAVIS_TAG-$BUILD_ENV-docs-$(date +'%Y%m%d').tar.gz  -C share/elastos/carrier html;
      fi;
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$ANDROID_ABI" == "" ]]; then
        tar -czf $TRAVIS_TAG-$BUILD_ENV-apps-$(date +'%Y%m%d').tar.gz bin etc;
      fi;
    fi

after_failure:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ -f core ]]; then
        sudo apt-get install gdb;
        echo bt | gdb ./elatests core;
      fi
    else
      if [[ -f /cores/core ]]; then
        echo bt | lldb -c /cores/core;
      fi
    fi

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: $TRAVIS_TAG-$BUILD_ENV*.tar.gz
  skip_cleanup: true
  on:
    tags: true
    # branches:
    #   only:
    #     - master
