version: 2

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
        environment:
          BUILD_ENV: linux
          CMAKE_URL: https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd /tmp && wget ${CMAKE_URL}
            tar -xzvf cmake-3.11.4-Linux-x86_64.tar.gz
      - run:
          name: Build and test
          command: |
            export PATH=/tmp/cmake-3.11.4-Linux-x86_64/bin:${PATH}
            cd build && mkdir ${BUILD_ENV} && cd ${BUILD_ENV}
            cmake -DCMAKE_INSTALL_PREFIX=dist -DAUTO_CI_TEST=ON ../..
            make && sudo make install
            cd dist/bin && ./elatests.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
